import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <body className={`bg-neutral-100 ${inter.className} w-full overflow-x-hidden p-2 lg:p-4`}>
        <Header />
        <main className="flex flex-col w-full gap-8 md:gap-16 overflow-x-hidden">
            {children}
          </main>
      </body>
    </html>
  );
}
